import P from "./P";

export const metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <h1 className="page-title">Profile</h1>
      <P />
    </>
  );
};

export default page;
