export const metadata = {
  title: "Settings",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <h1 className="page-title">Settings</h1>
    </>
  );
};

export default page;
